### ISSUE TITLE
Running the Step functions pipeline fails with "Essential Container Exited" error

### ISSUE THREAD

**Issue by sathishc** [awslabs/realtime-fraud-detection-with-gnn-on-dgl#1192]
Running the Step functions pipeline fails with "Essential Container Exited" error.

### Reproduction Steps

1) Use the solution at https://awslabs.github.io/realtime-fraud-detection-with-gnn-on-dgl/en/

2) Deploy the stack

3) Run the Step function pipeline; After the model is built, the task "Load the graph data to Graph database" fails with error "Essential Container Exited"

### Error Log

{
  "resourceType": "ecs",
  "resource": "runTask.sync",
  "error": "States.TaskFailed",
  "cause": "{\"Attachments\":[{\"Details\":[{\"Name\":\"subnetId\",\"Value\":\"subnet-00573893b6b2e85d6\"},{\"Name\":\"networkInterfaceId\",\"Value\":\"eni-029ede5b74b0b2c74\"},{\"Name\":\"macAddress\",\"Value\":\"0a:71:f2:44:c1:17\"},{\"Name\":\"privateDnsName\",\"Value\":\"ip-10-0-236-81.ec2.internal\"},{\"Name\":\"privateIPv4Address\",\"Value\":\"10.0.236.81\"}],\"Id\":\"f4fb56b2-63b6-4606-8853-0bef375ce9a2\",\"Status\":\"DELETED\",\"Type\":\"eni\"}],\"Attributes\":[{\"Name\":\"ecs.cpu-architecture\",\"Value\":\"x86_64\"}],\"AvailabilityZone\":\"us-east-1b\",\"ClusterArn\":\"arn:aws:ecs:us-east-1:690058322908:cluster/fraud-detection-on-dgl-trainingNestedStacktrainingNestedStackResourceAA446BCB-WPQE26XMSC6K-FraudDetectionClusterA78016CF-MePvRhDbSX8S\",\"Connectivity\":\"CONNECTED\",\"ConnectivityAt\":1681198609255,\"Containers\":[{\"ContainerArn\":\"arn:aws:ecs:us-east-1:690058322908:container/fraud-detection-on-dgl-trainingNestedStacktrainingNestedStackResourceAA446BCB-WPQE26XMSC6K-FraudDetectionClusterA78016CF-MePvRhDbSX8S/c797e127ba4f426daad6af5a4e5e6ed0/692a6f48-d798-4084-817e-9e46a6477b2c\",\"Cpu\":\"0\",\"ExitCode\":1,\"GpuIds\":[],\"Image\":\"366590864501.dkr.ecr.us-east-1.amazonaws.com/realtime-fraud-detection-with-gnn-on-dgl-rel:v2.0.4-9602326372374af5c2cab73a105108e2391a5d4dc8e4cd1a34153ee19d80cf88\",\"ImageDigest\":\"sha256:323092d76949bcd83b391ac2b7c1ae8f509b695c45daf934afa8b026bd2b0261\",\"LastStatus\":\"STOPPED\",\"ManagedAgents\":[],\"Memory\":\"512\",\"Name\":\"container\",\"NetworkBindings\":[],\"NetworkInterfaces\":[{\"AttachmentId\":\"f4fb56b2-63b6-4606-8853-0bef375ce9a2\",\"PrivateIpv4Address\":\"10.0.236.81\"}],\"RuntimeId\":\"c797e127ba4f426daad6af5a4e5e6ed0-2377118072\",\"TaskArn\":\"arn:aws:ecs:us-east-1:690058322908:task/fraud-detection-on-dgl-trainingNestedStacktrainingNestedStackResourceAA446BCB-WPQE26XMSC6K-FraudDetectionClusterA78016CF-MePvRhDbSX8S/c797e127ba4f426daad6af5a4e5e6ed0\"}],\"Cpu\":\"256\",\"CreatedAt\":1681198605741,\"DesiredStatus\":\"STOPPED\",\"EnableExecuteCommand\":false,\"EphemeralStorage\":{\"SizeInGiB\":20},\"ExecutionStoppedAt\":1681198952509,\"Group\":\"family:training-pipeline-load-graph-data\",\"InferenceAccelerators\":[],\"LastStatus\":\"STOPPED\",\"LaunchType\":\"FARGATE\",\"Memory\":\"1024\",\"Overrides\":{\"ContainerOverrides\":[{\"Command\":[\"--data_prefix\",\"s3://fraud-detection-on-dgl-frauddetectiondatabucketd4-2taoab8m8z4f/fraud-detection/neptune/bulk-load\",\"--temp_folder\",\"/mnt/efs\",\"--neptune_endpoint\",\"fraud-detection-on-dgl-transactiongraphclustera4fb-hlrs3g9fn1sa.cluster-c6o7urnzrhpo.us-east-1.neptune.amazonaws.com\",\"--neptune_port\",\"8182\",\"--region\",\"us-east-1\",\"--neptune_iam_role_arn\",\"arn:aws:iam::690058322908:role/fraud-detection-on-dgl-NeptuneBulkLoadRole819075D5-OV4JTGU49H5T\"],\"Environment\":[{\"Name\":\"MODEL_PACKAGE\",\"Value\":\"https://s3.us-east-1.amazonaws.com/fraud-detection-on-dgl-frauddetectiondatabucketd4-2taoab8m8z4f/fraud-detection/model_output/fraud-detection-model-1681196275158/output/model.tar.gz\"},{\"Name\":\"JOB_NAME\",\"Value\":\"fraud-detection-model-1681196275158\"},{\"Name\":\"GRAPH_DATA_PATH\",\"Value\":\"https://s3.us-east-1.amazonaws.com/fraud-detection-on-dgl-frauddetectiondatabucketd4-2taoab8m8z4f/fraud-detection/processed-data/jr_0a29416eb432e6dda1de0e59d7121d9f8c42b4faf2c192411f5566b62f08da61\"}],\"EnvironmentFiles\":[],\"Name\":\"container\",\"ResourceRequirements\":[]}],\"InferenceAcceleratorOverrides\":[]},\"PlatformVersion\":\"1.4.0\",\"PullStartedAt\":1681198616969,\"PullStoppedAt\":1681198640143,\"StartedAt\":1681198648874,\"StartedBy\":\"AWS Step Functions\",\"StopCode\":\"EssentialContainerExited\",\"StoppedAt\":1681198975736,\"StoppedReason\":\"Essential container in task exited\",\"StoppingAt\":1681198962812,\"Tags\":[],\"TaskArn\":\"arn:aws:ecs:us-east-1:690058322908:task/fraud-detection-on-dgl-trainingNestedStacktrainingNestedStackResourceAA446BCB-WPQE26XMSC6K-FraudDetectionClusterA78016CF-MePvRhDbSX8S/c797e127ba4f426daad6af5a4e5e6ed0\",\"TaskDefinitionArn\":\"arn:aws:ecs:us-east-1:690058322908:task-definition/training-pipeline-load-graph-data:1\",\"Version\":6}"
}

--- 

This is :bug: Bug Report

**Comment by sathishc** [comment]
Found this in the ECS console. 

Task stopped at: 11/04/2023, 14:30:18 UTC
ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: Failed to resolve "fs-035b24b131dc6bcc2.efs.us-east-1.amazonaws.com" - check that your file system ID is correct, and ensure that the VPC has an EFS mount target for this file system ID. See https://docs.aws.amazon.com/console/efs/mount-dns-name for more detail. Attempting to lookup mount target ip address using botocore. Failed to import necessary dependency botocore, please install botocore first. : unsuccessful EFS utils command execution; code: 1

**Comment by zxkane** [comment]
It's resolved in v2.0.5. Any issue let me know.
