### ISSUE TITLE
How leverage the repo to do customization?

### ISSUE THREAD

**Issue by welkinwalker** [awslabs/realtime-fraud-detection-with-gnn-on-dgl#32]
## :question: General Issue
There are many steps in the StepFunction, I don't know what each step is doing there? Can you give some explanation on the workflow of each step?

## :question: How to do customization?
If I want to perform a customization with the code, can you give me some guidance on how to get started? If you can provide a customization demo, that would be nicer.

**Comment by zxkane** [comment]
Thanks for your interesting for this solution. Will add related doc for explaining the detail of the steps of model training and deployment.

**Comment by zxkane** [comment]
resolved by #201 

see online doc at https://awslabs.github.io/realtime-fraud-detection-with-gnn-on-dgl/en/
