### ISSUE TITLE
Embedded stack arn:aws:cloudformation:us-east-1:578053008623:stack/fraud-detection-on-dgl-dashboardNestedStackdashboardNestedStackResourceB80305B3-1QLN9Y8UK7DTK/bc188160-343f-11ed-96bf-12d3ddd822cb was not successfully created: The following resource(s) failed to create: [FraudDetectionDashboardAPID13F00C7].

### ISSUE THREAD

**Issue by TonyBautistaXD** [awslabs/realtime-fraud-detection-with-gnn-on-dgl#817]
Getting this error when running the stack in automatic deployment.

### Reproduction Steps

Just ran the stack with the automatic process.

### Error Log

Embedded stack arn:aws:cloudformation:us-east-1:578053008623:stack/fraud-detection-on-dgl-dashboardNestedStackdashboardNestedStackResourceB80305B3-1QLN9Y8UK7DTK/bc188160-343f-11ed-96bf-12d3ddd822cb was not successfully created: The following resource(s) failed to create: [FraudDetectionDashboardAPID13F00C7].-->
--- 

This is :bug: Bug Report

**Comment by zxkane** [comment]
Thanks for reporting this issue.

Could you check the root failure cause of nested dashboard stack that is in deleted state?

It's probably caused by Appsync service is not enabled in that region. Pls redeploy it after the Appsync service is enabled.

**Comment by TonyBautistaXD** [comment]
Hello, yeah I think that is the error. Got this in that stack.

Failed to assume service-linked role arn:aws:iam::578053008623:role/aws-service-role/appsync.amazonaws.com/AWSServiceRoleForAppSync, please retry. (Service: AWSAppSync; Status Code: 403; Error Code: AccessDeniedException; Request ID: 8fb3b6dd-7ba6-4d11-b86f-9c3d8672c83e; Proxy: null)

**Comment by TonyBautistaXD** [comment]
Solved the issue. It was due to the rol being used not having the needed AppSync policy.

Thank you! and great stack by the way!
